### ISSUE TITLE
ORCA fitting

### ISSUE THREAD

**Issue by cleto94** [luisfabib/Hyscorean#1]
To whom it may concern,

I tried to simulate my HYSCORE spectrum by using the spin Hamiltonian parameters computed by ORCA quantum chemistry program.
However, after having loaded the proper .prop file, selected one of the nuclei parameters which I would like to use for the simulation and seen the message window displaying "Simulating ORCA system", an error message appear with the following:
**Simulation failed  due to errors:

Dot index is not supported for variables of this type.
Error in esfit_hyscorean>assess (line 1615)
EasySpinVersion=EasySpinInfo.Version;
Error in esfit_hyscorean>loadORCACallback (line 3493)
assess(0,funArgs{:});**

I have the currently stable version of EasySpin (5.2.28) and Matlab R2020a.
In attachment the zip folder with the HYSCORE spectrum and ORCA file.

Thank you very much for any help!

Best wishes
[ORCA fitting issue.zip](https://github.com/luisfabib/Hyscorean/files/4518798/ORCA.fitting.issue.zip)

**Comment by conradsz** [comment]
I get a similar error message, even for a standard fitting procedure using easyspin code:
'Dot index is not supported for variables of this type. [...]'
I think it is related to dot indexing the easyspin variables of that type: 'Sys.A = ...'

I also work with up-to-date easyspin and Matlab. 
Did standard fitting work for you?

Would appreciate any help or suggestions.

Best, C

**Comment by luisfabib** [comment]
Sorry for the late response. There was a backwards compatibility error with easyspin. In the last commits the compatibility with easyspin 6.0.x was introduced and broke the compatibility with versions 5.2.x. 

I fixed this and managed to run the fit for your data including the ORCA simulation.

**Comment by cleto94** [comment]
Thank you very much!
I will try again with other data I have collected so far.
Luis Fabregas <notifications@github.com> ha scritto:

> Sorry for the late response. There was a backwards compatibility  
> error with easyspin. In the last commits the compatibility with  
> easyspin 6.0.x was introduced and broke the compatibility with  
> versions 5.2.x.
>
> I fixed this and managed to run the fit for your data including the  
> ORCA simulation.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/luisfabib/Hyscorean/issues/1#issuecomment-691264424


-- 
Paolo Cleto Bruzzese
Faculty of Physics and Earth Sciences, MQF dept.
Leipzig University
Linnéstraße 5
04103 Leipzig
Phone: 0049 341 97 32609
